package nl.sebastiaan.iphonelauncher;

import android.app.*;import android.os.*;import android.content.*;import android.content.pm.*;import android.graphics.*;import android.graphics.drawable.*;import android.provider.Settings;import android.view.*;import android.view.inputmethod.InputMethodManager;import android.widget.*;import java.text.*;import java.util.*;

public class MainActivity extends Activity {
 LinearLayout root,grid,dock; EditText search; TextView clock; ArrayList<AppInfo> apps=new ArrayList<>(); Handler h=new Handler();
 int dp(float n){return (int)(n*getResources().getDisplayMetrics().density+.5f);} TextView tx(String s,float z){TextView t=new TextView(this);t.setText(s);t.setTextColor(Color.WHITE);t.setTextSize(z);t.setGravity(Gravity.CENTER);return t;} GradientDrawable bg(int c,float r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}
 public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Color.TRANSPARENT);getWindow().setNavigationBarColor(Color.BLACK);build();}
 void build(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(10),dp(18),dp(10),dp(8));root.setBackground(wall());setContentView(root);
  LinearLayout top=new LinearLayout(this);clock=tx("",16);clock.setTypeface(null,1);top.addView(clock,new LinearLayout.LayoutParams(0,dp(38),1));TextView cc=tx("◉  ▪",18);cc.setOnClickListener(v->controlCenter());top.addView(cc,new LinearLayout.LayoutParams(dp(60),dp(38)));root.addView(top);tick();
  search=new EditText(this);search.setHint("Search");search.setHintTextColor(0xffaaaaaa);search.setTextColor(Color.WHITE);search.setSingleLine();search.setPadding(dp(14),0,dp(14),0);search.setBackground(bg(0x55333333,22));root.addView(search,new LinearLayout.LayoutParams(-1,dp(44)));
  grid=new LinearLayout(this);grid.setOrientation(LinearLayout.VERTICAL);grid.setPadding(0,dp(14),0,dp(6));root.addView(grid,new LinearLayout.LayoutParams(-1,0,1));
  dock=new LinearLayout(this);dock.setGravity(Gravity.CENTER);dock.setPadding(dp(7),dp(7),dp(7),dp(7));dock.setBackground(bg(0x66333333,28));root.addView(dock,new LinearLayout.LayoutParams(-1,dp(88)));loadApps();
  search.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int d){}public void onTextChanged(CharSequence s,int a,int b,int c){render(s.toString());}public void afterTextChanged(android.text.Editable e){}});
 }
 Drawable wall(){PaintDrawable p=new PaintDrawable();p.setShaderFactory(new ShapeDrawable.ShaderFactory(){protected Shader resize(int w,int h){return new LinearGradient(0,0,0,h,0xff18254d,0xff05060a,Shader.TileMode.CLAMP);}});return p;}
 void tick(){clock.setText(new SimpleDateFormat("HH:mm",Locale.getDefault()).format(new Date()));h.postDelayed(()->tick(),30000);}
 void loadApps(){PackageManager pm=getPackageManager();Intent i=new Intent(Intent.ACTION_MAIN);i.addCategory(Intent.CATEGORY_LAUNCHER);for(ResolveInfo r:pm.queryIntentActivities(i,0))if(!r.activityInfo.packageName.equals(getPackageName()))apps.add(new AppInfo(r.loadLabel(pm).toString(),r.loadIcon(pm),r.activityInfo.packageName,r.activityInfo.name));Collections.sort(apps,(a,b)->a.label.compareToIgnoreCase(b.label));render("");}
 void render(String q){grid.removeAllViews();ArrayList<AppInfo> shown=new ArrayList<>();for(AppInfo a:apps)if(q.isEmpty()||a.label.toLowerCase().contains(q.toLowerCase()))shown.add(a);for(int n=0;n<shown.size();n+=4){LinearLayout row=new LinearLayout(this);for(int j=0;j<4;j++){int k=n+j;FrameLayout cell=new FrameLayout(this);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(0,dp(104),1);cp.setMargins(dp(3),dp(2),dp(3),dp(2));row.addView(cell,cp);if(k<shown.size()){AppInfo a=shown.get(k);ImageView iv=new ImageView(this);iv.setImageDrawable(a.icon);iv.setPadding(dp(5),dp(5),dp(5),dp(5));iv.setBackground(bg(Color.WHITE,20));FrameLayout.LayoutParams ip=new FrameLayout.LayoutParams(dp(62),dp(62));ip.gravity=Gravity.TOP|Gravity.CENTER_HORIZONTAL;cell.addView(iv,ip);TextView nm=tx(a.label,11);nm.setMaxLines(1);nm.setEllipsize(android.text.TextUtils.TruncateAt.END);FrameLayout.LayoutParams np=new FrameLayout.LayoutParams(-1,dp(25));np.gravity=Gravity.BOTTOM;cell.addView(nm,np);iv.setOnClickListener(v->launch(a));}}grid.addView(row,new LinearLayout.LayoutParams(-1,dp(104)));}renderDock();}
 void renderDock(){dock.removeAllViews();String[] wanted={"Telefoon","Berichten","Camera","Chrome"};for(String w:wanted){for(AppInfo a:apps)if(a.label.toLowerCase().contains(w.toLowerCase())){ImageView iv=new ImageView(this);iv.setImageDrawable(a.icon);iv.setPadding(dp(5),dp(5),dp(5),dp(5));iv.setBackground(bg(Color.WHITE,18));iv.setOnClickListener(v->launch(a));dock.addView(iv,new LinearLayout.LayoutParams(0,dp(68),1));break;}}TextView all=tx("☷",28);all.setOnClickListener(v->{search.requestFocus();((InputMethodManager)getSystemService(INPUT_METHOD_SERVICE)).showSoftInput(search,InputMethodManager.SHOW_IMPLICIT);});dock.addView(all,new LinearLayout.LayoutParams(0,dp(68),1));}
 void launch(AppInfo a){try{Intent i=new Intent();i.setComponent(new ComponentName(a.pkg,a.cls));startActivity(i);}catch(Exception e){}}
 void controlCenter(){Dialog d=new Dialog(this);LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.setPadding(dp(18),dp(20),dp(18),dp(20));b.setBackground(bg(0xee20232c,30));TextView t=tx("Control Center",24);t.setGravity(Gravity.LEFT);b.addView(t,new LinearLayout.LayoutParams(-1,dp(50)));LinearLayout r=new LinearLayout(this);for(String s:new String[]{"Wi‑Fi","Bluetooth","Focus","Vliegtuigmodus"}){TextView x=tx(s,14);x.setBackground(bg(0xff3a3d46,20));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(70),1);p.setMargins(dp(4),dp(4),dp(4),dp(4));r.addView(x,p);}b.addView(r);Button set=new Button(this);set.setText("Kies standaard launcher");set.setOnClickListener(v->{startActivity(new Intent(Settings.ACTION_HOME_SETTINGS));d.dismiss();});b.addView(set);Button close=new Button(this);close.setText("Sluiten");close.setOnClickListener(v->d.dismiss());b.addView(close);d.setContentView(b);if(d.getWindow()!=null)d.getWindow().setBackgroundDrawable(new ColorDrawable(Color.TRANSPARENT));d.show();}
 static class AppInfo{String label,pkg,cls;Drawable icon;AppInfo(String l,Drawable i,String p,String c){label=l;icon=i;pkg=p;cls=c;}}
}
